services:
  app:
    build: .
    container_name: rag-chat-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - loki-network

  db:
    image: postgres:15-alpine
    container_name: rag-chat-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - app-logs:/logs
    networks:
      - loki-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag-chat-pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - loki-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - app-logs:/logs
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - loki
    networks:
      - loki-network

volumes:
  db-data:
  app-logs:

networks:
  loki-network:
    driver: bridge
