services:
  app:
    build: .
    container_name: rag-chat-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: rag-chat-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag-chat-pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data:
